apiVersion: cache.clinia-test.com/v1alpha1
kind: ClientApp
metadata:
  labels:
    app.kubernetes.io/name: clientapp
    app.kubernetes.io/instance: clientapp-sample
    app.kubernetes.io/part-of: clinia-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: clinia-test
  name: clientapp-sample
spec:
  name: clientapp-sample
  image: 'nginx:latest'
  port: 8080
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  replicas: 3
  env:
    - name: REDIS_HOST
      value: 'redis-master'
    - name: REDIS_PORT
      value: '6379'
