name: Docker Build/Push and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ECR_REPOSITORY: clinia-test
  TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMG: '${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.TAG }}'
        run: |
          echo ${{ env.IMG }}
          make docker-build 
          make docker-push
      - name: Update kube config
        run: |
          aws eks update-kubeconfig --name tf-juliusoh-eks-cluster-us-west-1 --region us-west-1
      - name: Update deployment
        env:
         IMG: '${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.TAG }}'
        run: |
          make deploy IMG=${{ env.IMG }}